branch-defaults:
  master:
    environment: RedirFront-env-2
environment-defaults:
  RedirFront-env-2:
    branch: null
    repository: null
global:
  application_name: redir-front
  default_ec2_keyname: redir-front
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Node.js running on
    64bit Amazon Linux/4.4.4
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
